[book]
authors = ["Jalal"]
language = "en"
src = "src"
title = "ReliNow Protocol Documentation"

[output.html]
git-repository-url = "https://github.com/dimaland1/Relinow"
edit-url-template = "https://github.com/dimaland1/Relinow/edit/main/docs/src/{path}"
